services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./Backend
    ports:
      - "5001:5000"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - MONGODB_URI=mongodb://mongo:27017/wildfire
    depends_on:
      - mongo
      - ml-service

  ml-service:
    build: ./MlService
    ports:
      - "8000:8000"
    volumes:
      - ./MlService/Models:/app/models

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y mongodb-database-tools &&
        docker-entrypoint.sh mongod
      "
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: